# Generated by Django 4.2.10 on 2024-06-04 09:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_done_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(default=api.models.get_next_day),
        ),
    ]
